- .gitignore
- hatchery/Cargo.toml
Fixed git dependency and added Cargo.lock to gitignore
> Fixed git dependency and added Cargo.lock to gitignore

- Makefile
- dallo/src/lib.rs
- dallo/src/state.rs
- hatchery/src/world.rs
- hatchery/tests/fibonacci.rs
- modules/box/src/lib.rs
- modules/callcenter/src/lib.rs
- modules/counter/src/lib.rs
- modules/fibonacci/Cargo.toml
- modules/fibonacci/src/lib.rs
- modules/stack/src/lib.rs
- modules/vector/src/lib.rs
> Fix alignment issues

- dallo/Cargo.toml
- dallo/src/lib.rs
- hatchery/Cargo.toml
- modules/box/Cargo.toml
- modules/callcenter/Cargo.toml
- modules/counter/Cargo.toml
- modules/fibonacci/Cargo.toml
- modules/stack/Cargo.toml
- modules/vector/Cargo.toml
This makes clippy happier with the workspace.
> Make std feature default in dallo

- dallo/src/state.rs
- hatchery/src/lib.rs
- hatchery/src/world.rs
- hatchery/src/world/event.rs
- hatchery/tests/boxen.rs
- hatchery/tests/callcenter.rs
- hatchery/tests/counter.rs
- hatchery/tests/events.rs
- hatchery/tests/fibonacci.rs
- hatchery/tests/stacked.rs
- hatchery/tests/vector.rs
- modules/Cargo.toml
- modules/callcenter/src/lib.rs
- modules/counter/src/lib.rs
- modules/eventer/Cargo.toml
- modules/eventer/src/lib.rs
> Introduce event system

- dallo/src/state.rs
- dallo/src/types.rs
- hatchery/src/instance.rs
- hatchery/src/world.rs
- hatchery/src/world/stack.rs
- hatchery/tests/callcenter.rs
- modules/callcenter/src/lib.rs
> Add `caller` host function

- hatchery/Cargo.toml
- hatchery/src/error.rs
- hatchery/src/instance.rs
- hatchery/src/world.rs
- hatchery/src/world/event.rs
- hatchery/src/world/store.rs
- hatchery/tests/points.rs
> Add module metering

- dallo/Cargo.toml
- dallo/src/helpers.rs
- dallo/src/state.rs
- dallo/src/types.rs
- hatchery/Cargo.toml
- hatchery/src/error.rs
- hatchery/src/instance.rs
- hatchery/src/world.rs
> Use bytecheck to deserialize safely

- .github/workflows/build.yml
Quite self explanatory. This makes the checks run much faster.
> Run CI on self-hosted runner

- vmx/Cargo.toml
- vmx/src/error.rs
- vmx/src/instance.rs
- vmx/src/lib.rs
- vmx/src/linear.rs
- vmx/src/memory_handler.rs
- vmx/src/module.rs
- vmx/src/session.rs
- vmx/src/types.rs
- vmx/src/util.rs
- vmx/src/vm.rs
- vmx/tests/callcenter.rs
- vmx/tests/counter.rs
File backed mmap linear memory and commit mechanism
> File backed mmap linear memory and commit mechanism

- uplink/src/handlers.rs
- vmx/src/linear.rs
- vmx/src/memory_handler.rs
- vmx/tests/box.rs
Linear memory grow function implementation with refactorings and new constants.
It makes the box_set_get test pass.
> Linear memory grow function implementation

- modules/callcenter/src/lib.rs
- uplink/src/debug.rs
- uplink/src/state.rs
- uplink/src/types.rs
- vmx/src/imports.rs
- vmx/src/instance.rs
- vmx/src/linear.rs
- vmx/src/vm.rs
- vmx/tests/callcenter.rs
Ported all Callcenter tests exept the "cc_caller", which needs some extra features.
> RawQuery, RawTransaction working.

- modules/callcenter/src/lib.rs
- uplink/src/state.rs
- vmx/src/imports.rs
- vmx/src/session.rs
- vmx/tests/callcenter.rs
This completes the `Callcenter` test ports
> Caller implementation

- modules/eventer/src/lib.rs
- uplink/src/lib.rs
- uplink/src/state.rs
- vmx/src/event.rs
- vmx/src/imports.rs
- vmx/src/instance.rs
- vmx/src/session.rs
- vmx/tests/events.rs
> Implement event emission functionality 

- piecrust/src/vm.rs
- piecrust/tests/deploy_with_id.rs
Implemented deploy_with_id
Solves issue #108
> Implemented deploy_with_id

- piecrust-uplink/src/types.rs
This is necessary to ensure we can create raw transactions and queries from within modules, assuming we already have serialized data.
> Add `from_parts` to `RawQuery` and `RawTransaction`

- modules/box/src/lib.rs
- modules/callcenter/src/lib.rs
- modules/counter/src/lib.rs
- modules/debugger/src/lib.rs
- modules/eventer/src/lib.rs
- modules/everest/src/lib.rs
- modules/fallible_counter/counter/src/lib.rs
- modules/fallible_counter/src/lib.rs
- modules/fibonacci/src/lib.rs
- modules/host/src/lib.rs
- modules/spender/src/lib.rs
- modules/stack/src/lib.rs
- modules/vector/src/lib.rs
> Remove `#![no_main]` from modules

- README.md
- modules/callcenter/src/lib.rs
- modules/self_snapshot/src/lib.rs
- modules/spender/src/lib.rs
- piecrust-uplink/src/state.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
- piecrust/tests/box.rs
- piecrust/tests/callcenter.rs
- piecrust/tests/cold-reboot/src/main.rs
- piecrust/tests/counter.rs
- piecrust/tests/debug.rs
- piecrust/tests/deploy_with_id.rs
- piecrust/tests/events.rs
- piecrust/tests/fallible.rs
- piecrust/tests/fibonacci.rs
- piecrust/tests/height.rs
- piecrust/tests/host.rs
- piecrust/tests/persistence.rs
- piecrust/tests/points.rs
- piecrust/tests/self_snapshot.rs
- piecrust/tests/session_commit.rs
- piecrust/tests/stacked.rs
- piecrust/tests/vector.rs
> Make `transact` and `query` take arguments by reference

- piecrust/Cargo.toml
- piecrust/src/error.rs
Error Infrastructure Enhancement
Implements #132
> Error Infrastructure Enhancement

- piecrust/Cargo.toml
- piecrust/src/commit/diff_data.rs
- piecrust/src/commit/module_commit.rs
- piecrust/src/commit/module_commit_bag.rs
Switch to the qbsdiff crate.
Implements #150
> Qbsdiff switch

- piecrust/src/lib.rs
> Update Atomicity description

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- First `piecrust` release
- First `piecrust-uplink` release
> Release `0.1.0`

- piecrust/CHANGELOG.md
Updated changelog with information about the merged implementation of issue 162.
Relates to issue #162
> Updated changelog for the implementation of issue 162

- piecrust-uplink/src/types.rs
- piecrust/CHANGELOG.md
Implement Display for ModuleId
This is needed in Rusk.
Implements #178
> Implement Display for ModuleId

- modules/Cargo.toml
- modules/README.md
- modules/merkle/Cargo.toml
- modules/merkle/src/lib.rs
- piecrust/tests/merkle.rs
Included is a test that entails inserting multiple leaves while querying the root. The obtained roots are then all compared together, ensuring they're all different.
Resolves: #197
> Add example merkle tree module

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add support for the `feed` import [#243]
- Add `Error::Infallible` variant
- Add `Error::MissingHostData` variant
- Add `Error::MissingHostQuery` variant
- Add `Error::Utf8` variant
- Add `CallReceipt` struct
- Change signature of `SessionDataBuilder::insert` to return an error on serialization
- Handle possible errors in imports
- Handle error on deserializing contract metadata
- Change signature of `Session::deploy` to take `points_limit`
- Change signature of `Session::call` to take `points_limit`
- Change signature of `Session::call_raw` to take `points_limit`
- Change signature of `Session::call` to return `CallReceipt`
- Change signature of `Session::call_raw` to return `CallReceipt`
- Remove `Session::set_point_limit`
- Remove `Session::take_events`
- Remove `Session::spent`
- …
> Release 0.7.0

- contracts/c-example/build.sh
- contracts/c-example/contract.c
- piecrust/CHANGELOG.md
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/tests/bounds.rs
> Fix out-of-bounds memory access

- crumbles/CHANGELOG.md
- crumbles/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/instance.rs
- piecrust/src/store/memory.rs
- piecrust/src/store/tree.rs
This likely fixes the downstream [rusk issue](https://github.com/dusk-network/rusk/issues/1033).
> Fix contract/host heap access

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/instance.rs
- piecrust/src/store.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
We take a moment to check for unused dependencies in the crate, and upgrade when applicable.
> Remove unused dependencies and upgrade to latest versions

- contracts/host/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/session.rs
- piecrust/src/vm.rs
- piecrust/tests/host.rs
Reverts dusk-network/piecrust#328
> Revert "Allow for a `HostQuery` to take `&mut Session`"

- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
> Revert "One instance per contract function call"

- piecrust/CHANGELOG.md
- piecrust/src/session.rs
- piecrust/src/store/metadata.rs
- piecrust/src/store/session.rs
- piecrust/tests/persistence.rs
> Fix self ID on migrate

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
Bump Piecrust to release 0.19.0 and Uplink to release 0.12.0
> Bump Piecrust release 0.19.0 and Uplink release 0.12.0

- crumbles/README.md
- piecrust-uplink/README.md
> Add README for Crumbles

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
piecrust: bump version to 0.25.0
> piecrust: bump version to 0.25.0

- piecrust/CHANGELOG.md
- piecrust/src/session.rs
See also dusk-network/rusk#3341
> piecrust: add Session::set_meta

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust-uplink/src/serde_support.rs
> uplink: change event data to hex serialization instead of base64

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/Cargo.toml
piecrust-uplink: bumped version to 0.18.0
> piecrust-uplink: bumped version to 0.18.0

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
piecrust: version-0.28.1
addresses issue #440
> piecrust: version-0.28.1

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/error.rs
> uplink: Derive `Eq` and `PartialEq` on `ContractError`
