dusk-network/piecrust

- hatchery/src/instance.rs
- hatchery/src/lib.rs
- hatchery/src/snapshot.rs
- hatchery/src/storage_helpers.rs
- hatchery/src/world.rs
- hatchery/tests/boxen.rs
World persist and restore functionality.
State of all modules can be persisted and then restored, without redeployment of modules.
Implemented mechanism is verified by test `world_persist_restore` contained in file `boxen.rs`.
This PR solves issue #26.
> World persist and restore

- dallo/src/helpers.rs
- dallo/src/lib.rs
- dallo/src/state.rs
- dallo/src/types.rs
- hatchery/src/instance.rs
- hatchery/src/memory.rs
- hatchery/src/world.rs
- hatchery/src/world/event.rs
- hatchery/src/world/stack.rs
- hatchery/tests/boxen.rs
- hatchery/tests/callcenter.rs
- hatchery/tests/counter.rs
- hatchery/tests/stacked.rs
- hatchery/tests/vector.rs
- modules/box/src/lib.rs
- modules/callcenter/src/lib.rs
- modules/counter/src/lib.rs
- modules/eventer/src/lib.rs
- modules/everest/src/lib.rs
- modules/fibonacci/src/lib.rs
- modules/self_snapshot/src/lib.rs
- modules/stack/src/lib.rs
- modules/vector/src/lib.rs
Change lengths to use unsigned `u32`s everywhere
Change argument and return passing to use the serialized length of the value, rather than the encoded position.
fixes #30
> Add RawQuery, RawTransaction, RawResult.

- dallo/src/helpers.rs
- dallo/src/lib.rs
- dallo/src/state.rs
- hatchery/src/instance.rs
- hatchery/src/world.rs
- hatchery/tests/self_snapshot.rs
- modules/box/src/lib.rs
- modules/callcenter/src/lib.rs
- modules/counter/src/lib.rs
- modules/eventer/src/lib.rs
- modules/everest/src/lib.rs
- modules/fibonacci/src/lib.rs
- modules/self_snapshot/src/lib.rs
- modules/stack/src/lib.rs
- modules/vector/src/lib.rs
Make `query`, `query_raw`, `caller`, `height` callable from a top-level function.
> Move the argument buffer handlnig to `dallo`

- dallo/src/lib.rs
- dallo/src/state.rs
- hatchery/src/world.rs
- hatchery/src/world/event.rs
- hatchery/src/world/stack.rs
- hatchery/tests/points.rs
- modules/Cargo.toml
- modules/spender/Cargo.toml
- modules/spender/src/lib.rs
The calls work in the context of the running module. `spend` returns the points spent by the running module, while `limit` returns the point limit for the currently executing module.
Resolves: #46
> Add `spent` and `limit` host calls

- dallo/src/lib.rs
- dallo/src/state.rs
- hatchery/src/lib.rs
- hatchery/src/world.rs
- hatchery/src/world/native.rs
- hatchery/tests/host.rs
- modules/Cargo.toml
- modules/host/Cargo.toml
- modules/host/src/lib.rs
This introduces a new host import `nq`, allowing modules to execute arbitrary queries that are executed on the host and defined upstream via the `NativeQuery` trait.
Resolves #49
> Add host module support

- .cargo/config.toml
- Makefile
- vmx/src/bytecode_macro.rs
This shows that module writers can control the stack size of their module by setting `link-args` to the appropriate value. In our case, for the tests we could probably do with an even smaller number than 1 WASM page.
This PR also ensure we build to the root `target` directory so as to facilitate a `make modules`-then-`cargo clean` workflow.
> Set default module stack size to 1 WASM page

- Makefile
- modules/box/Cargo.toml
- modules/callcenter/Cargo.toml
- modules/counter/Cargo.toml
- modules/debugger/Cargo.toml
- modules/eventer/Cargo.toml
- modules/everest/Cargo.toml
- modules/fibonacci/Cargo.toml
- modules/host/Cargo.toml
- modules/micro/Cargo.toml
- modules/self_snapshot/Cargo.toml
- modules/spender/Cargo.toml
- modules/stack/Cargo.toml
- modules/vector/Cargo.toml
- uplink/Cargo.toml
- uplink/src/handlers.rs
The global allocator can either be set by the user, or by the uplink when selecting the `wee_alloc` feature.
Resolves #68
> Make `wee_alloc` optional

- vmx/src/session.rs
- vmx/tests/session_commit.rs
Last commits loaded only into (session's) fresh module' memories
Solves #91
> Last commits loaded only into (session's) fresh module' memories

- modules/everest/src/lib.rs
- uplink/src/lib.rs
- uplink/src/state.rs
- vmx/Cargo.toml
- vmx/src/error.rs
- vmx/src/imports.rs
- vmx/src/instance.rs
- vmx/src/session.rs
- vmx/tests/height.rs
Host data can be anything that can be serialized and offered up to a
module for consumption, from the height of the blockchain - included as
an example in the tests, to complex data.
Resolves #81
> Add host metadata support

- piecrust/src/instance.rs
- piecrust/src/memory_handler.rs
- piecrust/src/session.rs
- piecrust/src/vm.rs
- piecrust/tests/host.rs
Session and memory handler borrow VM immutably rather than clone the VM,
this PR also introduces an internal mutability for commits db in VM.
Addresses issue #113
> Session and memory handler borrow VM immutably

- piecrust-uplink/src/state.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
Added CheckBytes derivation to ModuleError - this is needed to fix Rusk serialization problem, at the same time it fixes the only struct/enum in Piecrust which has Archive derivation yet is lacking CheckBytes derivation.
Fixes issue #116
> Added CheckBytes derivation to ModuleError

- piecrust/src/imports.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
- piecrust/src/session/call_stack.rs
Ensures a module is only ever instantiated once per session, by using a map in the call stack. If an instance already exists in an instance map, then an element is appended without creating a new instance. If an instance does not exist in the map, a new one is created and then a new element appended to the stack.
Resolves #122
> Enforce a single instance per module

- piecrust/src/commit.rs
These functions are added to be able to go back and forth between the commit IDs and their inner byte arrays, for ease of serialization.
> Add `from_bytes` and `to_bytes` to commit IDs

- modules/callcenter/src/lib.rs
- modules/crossover/src/lib.rs
- piecrust-uplink/src/helpers.rs
- piecrust-uplink/src/state.rs
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
- piecrust/src/session/call_stack.rs
- piecrust/src/store/session.rs
- piecrust/src/vm.rs
- piecrust/tests/callcenter.rs
- piecrust/tests/crossover.rs
Each call, be it a transaction or a query, is now atomic - meaning it
will not change the state if it fails. This is also true for every
inter-contract call performed during said call.
This is achieved by a re-execution strategy. Since we have no way of
partially rolling back changes in memory, each failing call - and
inter-contract for that matter - will trigger a re-execution of all
historic calls in a session until said failure occurs. The failure is
then skipped, communicated to the caller, and execution proceeds until
the next error - if so the procedure is gone through again - or until it
succeeds.
Resolves #155
Resolves #156
> Implement call atomicity

- modules/everest/src/lib.rs
- piecrust-uplink/src/lib.rs
- piecrust-uplink/src/state.rs
- piecrust/src/imports.rs
- piecrust/tests/everest.rs
Host data has been renamed o meta data, access to which
is now optional, never panicking.
Described in issue #158
> Made meta data access option-based, never panicking

- README.md
- piecrust/src/error.rs
- piecrust/src/lib.rs
- piecrust/src/session.rs
- piecrust/src/store.rs
- piecrust/src/vm.rs
Adds some more comprehensive documentation to the `piecrust` crate. We ensure that at least the exposed API of the crate is covered.
See also: #103
> Add some documentation to `piecrust`

- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Added uplink::owner and uplink::self_id. [#158]
- Implemented Display for ModuleId. [#178]
- Added persistence for module metadata. [#167]
- Added `DeployData` and `DeployDataBuilder`. [#158]
- Added contract constructor mechanism. [#93]
- Added caching of module compilation outputs. [#162]
- Derive `Debug` for `Session` and `VM`
- Changed deploy API to accept `Into<DeployData>`. [#158]
- Made modules compile at deploy time rather than on first query/transaction time. [#162]
- Removed errant print statements.
- Removed SELF_ID export from contracts. [#167]
[0.2.0]: https://github.com/dusk-network/piecrust/releases/tag/v0.2.0
> Release `0.2.0`

- piecrust/Cargo.toml
This is necessary due to the failure in https://github.com/dusk-network/piecrust/pull/140
> Lock `wasmer` to version `3.1`

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/handlers.rs
- piecrust-uplink/src/lib.rs
- rust-toolchain.toml
This commit:
- Removes the old `alloc_panic_handler` feature flag.
- Removes the custom alloc panic handler.
- Ups the Rust nightly toolchain version.
Resolves #192
> Support new alloc panic handling

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Rename `DeployData` to `ModuleData`
- Remove `VM::genesis_session` in favor of config parameters in `VM::session`
- Add documentation for `piecrust-uplink::types`. [#139]
- Rename `ModuleError` enum variants to be upper case.
- Remove deprecated `alloc_error_handler`. [#192]
[0.3.0]: https://github.com/dusk-network/piecrust/compare/v0.2.0...v0.3.0
> Release `0.3.0`

- modules/box/Cargo.toml
- modules/callcenter/Cargo.toml
- modules/constructor/Cargo.toml
- modules/counter/Cargo.toml
- modules/crossover/Cargo.toml
- modules/debugger/Cargo.toml
- modules/eventer/Cargo.toml
- modules/everest/Cargo.toml
- modules/fallible_counter/Cargo.toml
- modules/fibonacci/Cargo.toml
- modules/host/Cargo.toml
- modules/merkle/Cargo.toml
- modules/metadata/Cargo.toml
- modules/micro/Cargo.toml
- modules/spender/Cargo.toml
- modules/stack/Cargo.toml
- modules/vector/Cargo.toml
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust-uplink/src/handlers.rs
`wee_alloc` is unmaintained, and as such shouldn't be used. `dlmalloc` is the default allocator for a `wasm32_unknown_unknown` target using the standard library and is a great candidate for use as the default global allocator in modules.
Resolves #199
> Remove `wee_alloc` and add `dlmalloc`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/session.rs
- piecrust/src/store.rs
- piecrust/src/store/module_session.rs
- piecrust/src/store/tree.rs
- piecrust/src/vm.rs
We use `dusk-merkle` to represent the merkle tree, and update it when a new commit is written to disk. The hash chosen for the leaves is `blake3`.
Resolves: #166
> Store Merkle tree of modules on disk

- modules/metadata/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/state.rs
- piecrust/CHANGELOG.md
- piecrust/src/module.rs
- piecrust/src/session.rs
- piecrust/tests/metadata.rs
This allows the consumer of the `piecrust` crate to define how large
they want the owner to be when offered to a module. Internally, we
handle the owner as a `Vec<u8>`, however it gets passed to a module as
a `[u8; N]`.
Resolves: #201
> Change `owner` type to `[u8; N]`

- piecrust/CHANGELOG.md
- piecrust/src/instance.rs
- piecrust/src/session.rs
- piecrust/src/store/module_session.rs
- piecrust/src/vm.rs
- piecrust/tests/commit.rs
This fix introduces a `SessionInner`, containing the previous contents of the `Session`, and changes the fields of a session to contain a `&'static mut SessionInner` and a reference count.
We can then internally clone a session, which aliases the reference to the `SessionInner`, allowing us to place a session directly in the `Env`.
It is then ensured that a session frees the `SessionInner` on `Drop`ping when the reference count reaches zero.
Resolves: #202
> Fix dangling pointer after session move

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `call` and associated functions and structs [#136]
- Add `dlmalloc` feature [#199]
- Add crate-specific README [#174]
- Change `module` named functions and items to `contract` [#207]
- Change signature of `owner` to return `[u8; N]` instead of `[u8; 32]` [#201] 
- Remove `State` struct [#209]
- Remove `query` and `transact` and associated functions and structs [#136]
- Remove `wee_alloc` feature [#199]
- Add `RawCall` re-export [#136]
- Add `Session::call` [#136]
- Add crate-specific README. [#174]
- Change `owner` parameter type in `ModuleData::builder` to be `[u8; N]` [#201] 
- Fix SIGSEGV caused by moving sessions with instantiate modules [#202]
- Remove `RawQuery/Transact` re-rexports [#136]
- Remove `Session::query/transact` [#136]
- Remove `query/transact` imports [#136] …
> Release `0.4.0`

- piecrust/CHANGELOG.md
- piecrust/src/store/mmap.rs
MAP_NORESERVE flag has been tested on devnet cluster (using https://github.com/dusk-network/rusk/commit/6dc5788cc6589a22ac8f372a90f3203ef235798d)
Resolves #213
> piecrust: add `MAP_NORESERVE` flag to mmap

- contracts/callcenter/src/lib.rs
- contracts/spender/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/lib.rs
- piecrust-uplink/src/state.rs
- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/tests/spender.rs
Allows for the point limit to be passed by a contract when performing a call.
Resolves #216
> Handle contract-passed points_limit

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `Session::call_raw` allowing for deferred (de)serialization [#218]
- Add `MAP_NORESERVE` flag to `mmap` syscall [#213]
- Include `points_limit` in `c` import [#216]
- Add `call_with_limit` and `call_raw_with_limit` [#216]
- Include `points_limit` in the `c` external [#216]
[piecrust 0.5.0]: https://github.com/dusk-network/piecrust/compare/v0.4.0...v0.5.0
[piecrust-uplink 0.5.0]: https://github.com/dusk-network/piecrust/compare/v0.4.0...v0.5.0
> Release `0.5.0`

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `MAP_NORESERVE` flag to `mmap` syscall [#213]
[0.1.1]: https://github.com/dusk-network/piecrust/compare/v0.1.0...v0.1.1
> Release 0.1.1

- Makefile
- contracts/c-example/build.sh
- contracts/c-example/contract.c
- piecrust/CHANGELOG.md
- piecrust/src/instance.rs
- piecrust/tests/counter.rs
An experiment in using different languages to target the `piecrust` VM. It resulted in a contract, written in C, that calls the counter contract to increment the counter, and then calls it again to read the counter value. It then proceeds to return the value back to the caller.
As a consequence of the experiment, it was discovered that we don't really require the `__heap_base` export and as such it is removed in this PR.
> Add example contract written in C

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `Event` struct according to spec
- Impl `fmt::Display` for `ContractError`
- Emit debug line on panic handler [#222]
- Add `debug` feature [#222]
- Change `emit` extern to include topic
- Rename `MODULE_ID_BYTES` to `CONTRACT_ID_BYTES`
- Expose `extern`s only on feature `abi` [#222]
- Rename `std` feature to `abi` [#222]
- Rename `host_debug` to `hdebug` and use arg buffer [#222]
- Remove unused `height` extern [#222]
- Remove unused `snap` extern [#222]
- Add `debug` feature, gating debugging capabilities [#222]
- Change event handling to emit `piecrust-uplink::Event`
- Change `emit` export to include topic
- Remove `Into<PathBuf>` bound in `VM::new`
- Rename `host_debug` export to `hdebug` [#222]
- Fix memleak due to last contract instance not being reclaimed
in session.
- Remove …
> Release `0.6.0`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/lib.rs
This ensures that `piecrust` is the only crate required for defining and interacting with a VM, while also allowing for any compatible version of `piecrust-uplink` to be used.
> Re-export the contents of `piecrust-uplink` in `piecrust`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Re-export the entirety of `piecrust-uplink` [#234]
[0.6.1]: https://github.com/dusk-network/piecrust/compare/v0.6.0...piecrust-0.6.1
> piecrust: bump version to `0.6.1`

- piecrust/CHANGELOG.md
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/src/session.rs
- piecrust/src/store/metadata.rs
- piecrust/tests/commit.rs
- piecrust/tests/everest.rs
It is important to handle errors properly, especially when these errors occur due to possibly malicious entities - be it contract or callers - trying to attack a long lived instance of the virtual machine.
This PR does this by handling errors appropriately, in particular in the WASM imports.
> Expand error handling

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust-uplink/src/abi.rs
- piecrust-uplink/src/abi/state.rs
- piecrust-uplink/src/lib.rs
- piecrust-uplink/src/types.rs
- piecrust/src/lib.rs
- piecrust/src/store.rs
We add some crate level docs, ensuring the first page of `docs.rs` is not so barebones, and ensure all relevant functions have at least a small comment adorning them.
To be more explicit on the feature requirements of each function, we also add some compile-time shennanigans for us to detect when `docs.rs` is building our crate, to properly display the required features on each function and struct.
Resolves: #190
Resolves: #189
See-also: #195
> uplink: add more comprehensive documentation

- contracts/Cargo.toml
- contracts/invalid/Cargo.toml
- contracts/invalid/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/lib.rs
- piecrust/src/error.rs
- piecrust/src/instance.rs
- piecrust/src/store.rs
- piecrust/src/store/memory.rs
- piecrust/tests/validation.rs
Contract validation is performed during deployment of the contract, to ensure no invalid contracts ever "hit" the state. The following rules are employed:
- Argument buffer fits in the memory
- There is only one memory, and it's called "memory
- Every exported function matches the `f: i32 -> i32` calling convention
Resolves #157
> Add contract validation

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `Error::MemoryAccessOutOfBounds` [#249]
- Add `memmap2` dependency
- Change imports 
- Change diffing algorithm to not delegate growth to `bsdiff`
- Change memory growth algorithm to not require copying to temp file
- Fix  behavior of imports on  out of bounds pointers [#249]
- Fix SIGBUS caused by improper memory growth
[0.8.0]: https://github.com/dusk-network/piecrust/compare/v0.7.0...piecrust-0.8.0
> Piecrust release `0.8.0`

- crumbles/CHANGELOG.md
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Change commit write behavior to  write dirty pages instead of diffs [#253]
- Change memory backend  to use `crumbles` instead of `libc` directly  [#253]
- Remove `Session::squash_commit`  since it's irrelevant with the new commit behavior [#253]
- Remove `libc` dependency [#253]
- Remove `flate2` dependency [#253]
- Remove `qbsdiff` dependency [#253]
- Initial release
[piecrust 0.9.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.8.0...piecrust-0.9.0
[crumbles 0.1.0]: https://github.com/dusk-network/piecrust/releases/tag/crumbles-0.1.0
> Release `crumbles` and `piecrust`

- piecrust/CHANGELOG.md
- piecrust/src/store.rs
This was happening when a given contract was not modified during the creation of a new commit.
> piecrust: fix non-existing memory directory

- crumbles/CHANGELOG.md
- crumbles/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Remove re-execution in favor of micro-snapshots [#254]
- Fix non-existing memory directory when not modifying a contract
- Fix memory protection on snapshotting functions
[piecrust 0.9.1]: https://github.com/dusk-network/piecrust/compare/piecrust-0.9.0...piecrust-0.9.1
[crumbles 0.1.1]: https://github.com/dusk-network/piecrust/compare/crumbles-0.1.0...crumbles-0.1.1
> Hotfix `piecrust` and `crumbles`

- crumbles/CHANGELOG.md
- crumbles/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Change to use `crumbles::Mmap::set_len` on growing memory
- Add `Mmap::set_len` function
[piecrust 0.9.2]: https://github.com/dusk-network/piecrust/compare/piecrust-0.9.1...piecrust-0.9.2
[crumbles 0.1.2]: https://github.com/dusk-network/piecrust/compare/crumbles-0.1.1...crumbles-0.1.2
> Hotfix `crumbles` and `piecrust`

- crumbles/CHANGELOG.md
- crumbles/src/lib.rs
Small oversight in the usage of `File::into_raw_fd`, leading to files used by crumbles *never being closed*
> crumbles: fix file descriptor leak

- crumbles/CHANGELOG.md
- crumbles/Cargo.toml
- Fix files passed to `Mmap::from_file` never being closed
[0.1.3]: https://github.com/dusk-network/piecrust/compare/crumbles-0.1.2...crumbles-0.1.3
> crumbles: hotfix `0.1.3`

- crumbles/CHANGELOG.md
- crumbles/Cargo.toml
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `Session::memory_len` to get the length of a memory in session [#268]
- Change minimum number of pages to be 4
- Change reporting of memory to the host to be the total range of the memory
mapping available
- Fake guard pages are now removed
- Revert memory size on errors [#268]
- Fix reporting of memory size to `wasmer` [#268]
- Expose `arg_buf::with_arg_buf` to allow for custom argument buffer handling [#268]
- Change `AsRef<[u8]>` and `AsMut<[u8]>` implementations for `Mmap` to always
return the entire mapping
- Change segfault handler to no longer handle "Out of Bounds", since rust
already handles this correctly - with a panic
- Remove `Mmap::set_len`
- Remove `len` field from `MmapInner`
[piecrust 0.10.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.9.3...piecrust …
> `piecrust` release `0.10.0`

- Cargo.toml
- contracts/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/src/call_tree.rs
- piecrust/src/imports.rs
- piecrust/src/lib.rs
- piecrust/src/session.rs
- piecrust/src/session/call_stack.rs
- rust-toolchain.toml
Adds the call tree to the receipt of a call, allowing the host to understand which contract spent how much gas during the total execution. This tree can be iterated through, yielding `CallTreeElem` which contain various information about the call that was made. This also means code can be written downstream that branches on what each contract spent.
Resolves: #206
> Receive call tree after execution

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
Given that the return is meant to be the length of what is written by the host in the argument buffer, and this length is fixed for both functions, it can safely be removed.
> Return nothing from `owner` and `self_id`

- crumbles/CHANGELOG.md
- crumbles/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/instance.rs
- piecrust/src/store/memory.rs
- piecrust/src/store/tree.rs
`crumbles` now allows the user to specify the size of the mappings they require, as opposed to fixing the mappings to be tied to the 32-bit WASM specification - i.e. 64KiB page size and 64Ki pages. The user can now specify the logical size of the pages used by `crumbles::Mmap`, as well as their number. The page size has to be a multiple of the system page size, otherwise the dirty page tracking mechanism ceases to work.
> `crumbles`: support arbitrarily sized memory

- crumbles/CHANGELOG.md
- crumbles/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/store.rs
- piecrust/src/store/memory.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
This PR addresses an important scaling issue currently present with the page mapping mechanism.
Since there exists one file per contract page, and all pages must be accessible by the contract at any time, all files had to be iterated through and mapped to the address space region to be used as the contract's memory - *immediately* on first load. This will become a significant upfront cost for running a contract, especially once it becomes larger.
Here we introduce a mechanism where the pages are loaded on-demand, removing the upfront cost of loading a contract, and trading it in for more memory usage (2 bits per page).
> Map each contract page lazily

- crumbles/CHANGELOG.md
- crumbles/Cargo.toml
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `spent` field to `CallTreeElem` [#206]
- Add `call_tree` to `CallReceipt` [#206]
- Expose `CallTree` and `CallTreeElem` in the public API [#206]
- Add `CallTreeIter` to improve iteration over call tree [#206]
- Add `panic` import implementation [#271]
- Add `Error::ContractPanic` variant [#271]
- Adapt to use `LocateFile` - `crumbles`'s lazy page loading mechanism
- Adapt to `crumbles` needing `n_pages` and `page_size`
- Change return of `owner` and `self_id` to `()`
- Rename `StackElement` to `CallTreeElem` [#206]
- Allow for multiple initializations on a new memory [#271]
- Downcast `Error::RuntimeError` on each call boundary [#271]
- Remove `CallStack` in favor of `CallTree` [#206]
- Add call to `panic` in panic handler [#271]
- Add `panic` extern [#271]
- Change return of …
> Release `0.11.0`

- Makefile
- scripts/setup-compiler.sh
The compiler is downloaded and extracted to the target directory, and linked to the toolchains in the rustup directory, making it available to be used anyone in the system.
The compiler is available as under the `+dusk` option in rust tools, and is able to compile at least the `wasm32-unknown-unknown` target. It is released [here](https://github.com/dusk-network/rust/releases/tag/v0.0.0).
See-also: #280
> Use Dusk compiler for contracts

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/contract.rs
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
- piecrust/src/store.rs
- piecrust/src/store/memory.rs
- piecrust/src/store/tree.rs
- piecrust/src/vm.rs
- piecrust/tests/spender.rs
We switch WebAssembly runtime - from `wasmer` to `wasmtime` - to make
use of the features it has available, notably `memory64` support.
In the process we are one step further to having 64-bit contracts, and
have gotten rid of the 4 page minimum memory requirement.
See-also: https://github.com/dusk-network/piecrust/issues/281
> Switch from `wasmer` to `wasmtime`

- piecrust/CHANGELOG.md
- piecrust/src/store.rs
- piecrust/src/vm.rs
We do this by at `VM` instantiation time, checking if the module is correct for the native platform. If the module is not correct we compile it and write it back to disk. 
Resolves #287
> Fix loading state from other archs

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Support `memory64` smart contracts [#281]
- Add some `Error` variants:
* `InvalidFunction`
* `InvalidMemory`
- Add `once_cell` dependency
- Upgrade `dusk-merkle` to version `0.5`
- Change contract tree to be arity 4 and height 17 [#159]
- Maximum contract size is now 4TiB [#159]
- Change `Error::RuntimeError` variant to contain `dusk_wasmtime::Error`,
and changed `From` implementation
- Switch runtime from `wasmer` to `wasmtime`
- Remove `parking_lot` dependency
- Remove `colored` dependency
- Remove 4 page - 256KiB - minimum memory requirement for contracts
- Remove `Clone` derivation for `Error`
- Remove some `Error` variants, along with `From` implementations:
* `CompileError`
* `DeserializeError`
* `ExportError`
* `InstantiationError`
* `InvalidFunctionSignature`
* …
> Release `0.12.0`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `Session::memory_pages` allowing for inclusion  proofs of pages [#273]
- Change state tree to  distinguish between 32 and 64 bit smart contracts [#273]
[0.13.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.12.0...piecrust-0.13.0
> Release piecrust `0.13.0`

- contracts/callcenter/src/lib.rs
- crumbles/Cargo.toml
- crumbles/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/instance.rs
- piecrust/src/session.rs
- piecrust/tests/commit.rs
- piecrust/tests/growth.rs
> Fix post-error root calculation 

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/session.rs
- piecrust/src/vm.rs
Using a dummy engine instantiated with the default configuration resulted in conflicting signal handling on MacOS. This commit fixes this problem, allowing MacOS users to run.
> Fix improper use of mach_ports

- contracts/callcenter/src/lib.rs
- contracts/spender/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust-uplink/src/error.rs
- piecrust-uplink/src/types.rs
- piecrust/CHANGELOG.md
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/tests/callcenter.rs
- piecrust/tests/counter.rs
- piecrust/tests/spender.rs
This pull request enables a contract to access the reason behind a panic that occurs during an inter-contract call. It also includes enhancements to the inter-contract call functions, improving the clarity of arguments.
In specific updates, the enum variants of ContractError have been renamed to camel case. The Panic variant now includes a panic message as a String. The host ensures that this string is placed on the callee's argument buffer.
Resolves: #301
> Allow contracts access to panic information

- contracts/c-example/src/lib.rs
- contracts/callcenter/src/lib.rs
- contracts/spender/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust-uplink/src/error.rs
- piecrust/CHANGELOG.md
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/src/imports/wasm32.rs
- piecrust/src/imports/wasm64.rs
- piecrust/src/instance.rs
- piecrust/src/lib.rs
- piecrust/src/session.rs
- piecrust/tests/merkle.rs
- piecrust/tests/spender.rs
There's been a lot of confusion on the difference between `points` and `gas`.
The theory was that we would use different terminology here, and that there would be a one-to-one relationship between gas and points upstream. This would also ensure that the implementer would be careful in translating points to actual value.
However, as the reader will no doubt notice, this constitutes unnecessary cognitive overhead for no tangible benefit. This is due to the fact that a layer of translation between gas and value has to exist regardless of whether the `points/gas` distinction exists or not.
Therefore this PR changes the entire nomenclature of the project to use `gas`, as opposed to `points`, effectively eliminating this overhead.
> Change `points` terminology to `gas`

- piecrust-uplink/Cargo.toml
- piecrust/Cargo.toml
Bumps to `piecrust@0.14.0-rc.2` and `piecrust-uplink@0.9.0-rc.0`
> Bump version to `0.14.0-rc.2`

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- Add `ContractError::to_parts` and `ContractError::from_parts` functions [#301]
- Add `fn_name` and `fn_arg` as an argument to `call_raw` and `call_raw_with_limit` [#301]
- Change variable names and documentation to match the `gas` terminology as
opposed to `points`
- Rename `ContractError::Other` to `ContractError::Unknown` [#301]
- Change `Display` for `ContractError` to display messages [#301]
- Change `ContractError` variants to be CamelCase [#301]
- Remove `ContractError::from_code` function [#301]
- Remove `raw_call` as an argument of `call_raw` and `call_raw_with_limit` [#301]
- Remove `RawCall` and `RawResult` [#301]
[0.9.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.8.0...uplink-0.9.0
> uplink: Bump to v0.9.0

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Use `ContractError::to_parts` to write error messages to the argument buffer [#301]
- Change documentation to change terminology from `points` to `gas`
- Rename `CallReceipt::points_limit` and `CallReceipt::points_spent` to
`CallReceipt::gas_limit` and `CallReceipt::gas_spent` respectively
- Rename `Error::OutOfPoints` to `Error::OutOfGas`
- Rename `Error::ContractPanic` to `Error::Panic` to be more clear that the entire
execution panicked [#301]
- Upgrade `dusk-wasmtime` to version `15`
- De-instantiate modules after call [#296]
- Change `Session::memory_len` to return `Result<Option<usize>>`, and not
require a contract to be instantiated [#296]
- Remove `once_cell` dependency
- Fix improper use of mach_ports
- Fix inconsistent state root after erroring call [#296]
[0.14.0]: …
> piecrust: Bump to v0.14.0

- piecrust/CHANGELOG.md
- piecrust/src/store.rs
- piecrust/src/store/module.rs
Fixes recompiling the modules on VM instantiation when invalid ones are detected. This can happen in many circumstances, one of which is ingesting state produced under a different architecture or operating system.
> Fix module recompilation

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Fix module recompilation on invalid object code
[0.14.1]: https://github.com/dusk-network/piecrust/compare/piecrust-0.14.0...piecrust-0.14.1
> Hotfix `piecrust@0.14.1`

- contracts/metadata/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/src/imports/wasm32.rs
- piecrust/src/imports/wasm64.rs
- piecrust/tests/metadata.rs
Currently it is only possible for contract's to query for their own owners. This PR makes it possible for contract's to query for any other contract's owner as well.
This is achieved by modifying the `owner` import to accept a pointer to a contract ID in the calling contract's memory. If the passed pointer is non-null, the host reads the contract ID from the contract's memory, otherwise it is assumed to be the calling contract's.
If the contract queried for exists, its owner is emplaced in the calling contract's argument buffer, and 1 is returned, otherwise 0 is returned.
> Allow for querying a specific contract's owner

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Change `owner` import to accept the contract ID as argument and return
non-zero upon success
- Add `self_owner` function returning the owner of the calling contract
- Change `owner` function to take a `ContractId` as argument and return an `Option<[u8; N]>`
- Change `owner` extern to take a `*const u8` argument signifying the contract ID
[piecrust 0.15.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.14.1...piecrust-0.15.0
[uplink 0.10.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.9.0...uplink-0.10.0
> Release `piecrust@0.15.0` and `piecrust-uplink@0.10.0`

- contracts/Cargo.toml
- contracts/double_counter/Cargo.toml
- contracts/double_counter/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/session.rs
- piecrust/src/store.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
- piecrust/tests/persistence.rs
Bytecode migrations can now be performed using the `Session::migrate` function. This new function allows for passing in a closure that encodes a migration procedure. The procedure will have both contracts available in the state and is passed the new contract's temporary ID such that it can be called in just the same way as a regular contract. Once the procedure is executed without error the old contract is replaced with the new one and the session returned to the user.
Since it is possible that the `Session` is in an inconsistent state after an error in `Session::migrate`, the function takes the session by value, consuming it, and only returning it if no error was encountered.
Resolves: #313
> Add bytecode migrations

- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
Changes the instance reclamation code to allow for exactly one module instance per contract function call. This changes the way in which the node processes the state, leading to diverging state roots on errorring calls.
Simplifies the instance code by using a boolean to appropriately drop the instance. This allows the data in the struct to be passed around the `Env`, whilst fixing some bad dereferences previously occurring under certain situations.
Resolves: #325
> One instance per contract function call

- contracts/host/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/session.rs
- piecrust/src/vm.rs
- piecrust/tests/host.rs
This will allow for downstream to make use of a `Session` while defining host functions, enabling contracts to be called during their execution.
Resolves: #327
> Allow for a `HostQuery` to take `&mut Session`

- contracts/counter/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust-uplink/src/abi/helpers.rs
- piecrust/CHANGELOG.md
- piecrust/src/session.rs
- piecrust/tests/spender.rs
Support bytecheck-based integrity check of contract calls' arguments,
Implements issue #324
> support bytecheck-based integrity check of contract calls' arguments

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Change `call` and `feeder_call` functions to support `bytecheck`-based integrity check of arguments [#324]
- Add `Session::migrate` to allow for swapping contract code [#313]
- Upgrade `dusk-wasmtime` to version `17`
- Fix overflow in gas limit calculation in inter-contract call
- Add `wrap_call_unchecked` function for calls with no argument checking [#324]
- Change `wrap_call` function to support `bytecheck`-based integrity check of arguments [#324]
- Add `self_owner` function returning the owner of the calling contract
[piecrust 0.16.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.15.0...piecrust-0.16.0
[uplink 0.11.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.10.0...uplink-0.11.0
> Release 0.16.0

- piecrust/CHANGELOG.md
- piecrust/src/contract.rs
- piecrust/src/lib.rs
- piecrust/src/session.rs
- piecrust/tests/box.rs
- piecrust/tests/callcenter.rs
- piecrust/tests/cold-reboot/src/main.rs
- piecrust/tests/commit.rs
- piecrust/tests/constructor.rs
- piecrust/tests/counter.rs
- piecrust/tests/crossover.rs
- piecrust/tests/debugger.rs
- piecrust/tests/deploy_with_id.rs
- piecrust/tests/eventer.rs
- piecrust/tests/everest.rs
- piecrust/tests/feeder.rs
- piecrust/tests/fibonacci.rs
- piecrust/tests/growth.rs
- piecrust/tests/host.rs
- piecrust/tests/merkle.rs
- piecrust/tests/metadata.rs
- piecrust/tests/persistence.rs
- piecrust/tests/root.rs
- piecrust/tests/spender.rs
- piecrust/tests/stack.rs
- piecrust/tests/validation.rs
- piecrust/tests/vector.rs
`Session::migrate` is changed to allow for taking the owner of the previous contract, as opposed to it being mandatory to set a new owner.
This entailed numerous API change, the gist of which being that the `owner` is handled internally as a `Vec<u8>` as opposed to a `[u8; N]`. This puts some responsibility on the user of the crate to think about what this means for when the contracts call `owner` or `self_owner`. It is likely wise to only set owner which are always the same size.
Resolves #336
> piecrust: optional owner in `Session::migrate`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `ContractDataBuilder::owner` to allow for setting the owner of a contract
on deploy time [#336]
- Change `migrate` to take the owner of the contract being replaced if it is
not set by the caller [#336]
- Make `owner` field optional in `ContractData` and `ContractDataBuilder` [#336]
- Change `ContractData` and `ContractDataBuilder` to take a `Vec<u8>` as owner
instead of `[u8; N]` [#336]
- Use empty constructor arguments by default [#316]
- Upgrade `dusk-wasmtime` to version `18`
> piecrust: bump version to '0.17.0'

- piecrust/CHANGELOG.md
- piecrust/src/session.rs
- piecrust/tests/feeder.rs
> Allow feeder calls to set the gas limit

- piecrust/CHANGELOG.md
- piecrust/src/call_tree.rs
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
Fixing these required the introduction of an error variant called `Error::ArgumentBufferOverflow`, to handle possible instance of callers calling contracts with way too long arguments.
Resolves #343
> Fix audit-reported under/overflows

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Add `Error::ArgumentBufferOverflow` variant [#343]
- Fix possible under/overflows reported by audit [#343]
- Change `Session::feeder_call` and `Session::feeder_call_raw` to allow for the
caller to specify the gas limit [#344]
- Fix `Session::migrate` to replace the contract ID in the new contract's
metadata to the old contract's ID [#347]
[0.18.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.17.0...piecrust-0.18.0
> Release `0.18.0`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/instance.rs
In this version, `wasmtime` introduces a preliminary version of the [`winch`] compiler, which is ready to use on `x86` embeddings. They advise not using it in production just yet, but at least its ready for testing.
[`winch`]: https://github.com/bytecodealliance/wasmtime/releases/tag/v19.0.0
See-also: https://github.com/dusk-network/piecrust/issues/351
> Upgrade to `dusk-wasmtime` version `19`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Upgrade `dusk-wasmtime` to version `20`
[piecrust 0.18.1]: https://github.com/dusk-network/piecrust/compare/piecrust-0.18.0...piecrust-0.18.1
> `piecrust` release `0.18.1`

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/vm.rs
- piecrust/tests/spender.rs
Each byte stored in the WebAssembly linear memory of a contract is made to cost 4 units of fuel - in the units that wasmtime uses. This makes storing a single byte as expensive as, for example, multiplying or subtracting two numbers.
The `MemoryGrow` instruction is purposefully left with the default price - just like any other instruction, due the fact that expanding the size of the linear memory doesn't actually cost a lot of resources, owing to the fact that a page that is never written to is never written to disk.
A single contract's compiled bytecode will contain a header, encoding within it information about the cost per WebAssembly instruction. If these don't match the costs configured for the current `VM` instantiation, the contract will be recompiled, just as what happens if the …
> Make storage instructions cost

- contracts/metadata/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust/CHANGELOG.md
- piecrust/src/contract.rs
- piecrust/src/imports.rs
- piecrust/src/imports/wasm32.rs
- piecrust/src/imports/wasm64.rs
- piecrust/src/session.rs
- piecrust/src/store/session.rs
- piecrust/tests/metadata.rs
Enrich deploy method and contract's metadata with optional gas limit and gas price hint for free transactions,
Implements issue #357
> Enrich deploy method and contract's metadata with optional gas limit and gas price hint for free transactions

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Apply charging mechanism for host queries [#359]
- Add `HostQuery::execute` and `HostQuery::deserialize_and_price` [#359]
- Add support for metadata elements: free limit and free price hint [#357]
- Drop `Fn(&mut [u8], u32) -> u32` bound for `HostQuery` [#359]
- Make storage instructions cost 4 gas per byte [#359]
- Upgrade `dusk-wasmtime` to version `21.0.0-alpha` [#359]
- Add support for metadata elements: free limit and free price hint [#357]
[piecrust 0.20.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.19.0...piecrust-0.20.0
[uplink 0.13.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.12.0...uplink-0.13.0
> Release `piecrust@0.20.0`

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust-uplink/src/types.rs
- piecrust/src/session.rs
Removal of the 'charge' portion of the Economic Model scenario 3
Implements issue #365
> Removal of the 'charge' portion of the Economic Model scenario 3

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Remove economic protocol-related functionality
- Remove all economic protocol-related functionality
- Removed the 'charge' portion of the economic protocol [#365]
[uplink 0.14.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.13.0...uplink-0.14.0
[piecrust 0.21.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.20.0...piecrust-0.21.0
> `piecrust` release `0.21.0`

- contracts/eventer/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/config.rs
- piecrust/src/imports.rs
- piecrust/src/lib.rs
- piecrust/src/vm.rs
- piecrust/tests/eventer.rs
This PR introduces a cost to event emission proportional to the amount of bytes emitted, and at the same rate as a storage instruction. The rationale is that, while nodes are not necessarily required by protocol to hold this data like normal storage, it is still crucial data to hold for external applications, and contracts should be discouraged from emitting events that are "too large".
Hence, a payment at the same rate of storage seems appropriate for now. We may always choose to fine-tune this in a future protocol upgrade.
This should be the final round of pricing PRs, as I can't see the sense in pricing any other WebAssembly import offered to the contracts.
Resolves #359
> Price event bytes at the same rate as storage

- piecrust/CHANGELOG.md
- piecrust/src/session.rs
Introduces `deploy_raw` method for Piecrust.
Implements #371
> piecrust: introduce deploy_raw

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Added `deploy_raw` method for serialized constructor arguments [#371]
- Make each event byte cost the same as a storage byte [#359]
- Fix incomplete removal of economic protocol functionality
[piecrust 0.22.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.21.0...piecrust-0.22.0
[uplink 0.15.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.14.0...uplink-0.15.0
> Release 0.22.0

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/types.rs
According to the [cross crate considerations](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#cross-crate-considerations) of the Rust documentation, one should only implement `PartialEq` for local types, and not for foreign types.
As for implementing it on references... `PartialEq` already takes both operands by reference, making these implementations useless in practice.
Resolves: #375
> uplink: add `impl PartialEq<[u8; 32]> for ContractId`

- contracts/callcenter/src/lib.rs
- contracts/crossover/src/lib.rs
- contracts/spender/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
- piecrust-uplink/src/types.rs
- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/src/session.rs
- piecrust/tests/callcenter.rs
We remove the concept of a `ContractId` being "uninitialized" and all related functionality, and in its place put in an improved ABI, using an integer to signal whether there is a caller or not. These two concepts are semantically equivalent, with the exception that in the former the contract at "zero" `ContractId` is not a possible caller - instead being considered "uninitialized".
As a consequence, we can return `Option<ContractId>` from `piecrust_uplink::caller`, which is a much clearer and more ergonomic API.
> Remove the concept of an "uninitialized" `ContractId`

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Change `callee` import to return an integer
- Add `impl PartialEq<[u8; 32]> for ContractId` [#375]
- Change `callee` function to return `Option<ContractId>`
- Change `callee` ABI to return an integer
[piecrust 0.23.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.22.0...piecrust-0.23.0
[uplink 0.16.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.15.0...uplink-0.16.0
> Release `0.23.0`

- contracts/double_counter/src/lib.rs
- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/error.rs
- piecrust/CHANGELOG.md
- piecrust/src/error.rs
- piecrust/src/imports.rs
- piecrust/tests/deploy.rs
The path when a contract calls another contract which does not exist was not handled, and would lead to a panic of the entire execution when it does. This PR fixes this by introducing a new error path in the `c` import that *does not* revert, and a new `ContractError::DoesNotExist` variant.
> Fix behavior on calling non-existent contracts

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/abi/state.rs
Pretty self-explanatory. The `'static` bound was there because we though users should be stimulated to define their event types, but since this is not a real constraint, we remove it.
> Remove `'static` bound on `emit` topics

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- Fix behavior of calling a non-existent contract in `c` import
- Add `emit_raw` and `feed_raw` functions
- Add `ContractError::DoesNotExist` variant
- Remove `'static` bound on `emit` topics
[piecrust 0.24.0]: https://github.com/dusk-network/piecrust/compare/piecrust-0.23.0...piecrust-0.24.0
[uplink 0.17.0]: https://github.com/dusk-network/piecrust/compare/uplink-0.16.0...uplink-0.17.0
> Release 0.24.0

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/src/lib.rs
More scratch size allows for serializing more complex structures. This PR increases the scratch size from 64 bytes to 1024 bytes, leaving ample room for complex serializations.
Downstream in [`rusk`](https://github.com/dusk-network/rusk), we need this to be able to serialize a large vector of rewards to provisioners.
> uplink: increase scratch size to 1024

- piecrust/CHANGELOG.md
- piecrust/src/store.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
- piecrust/src/vm.rs
- piecrust/tests/root.rs
- piecrust/tests/spender.rs
Changed the state persistence representation into a delta-based representation in order to improve the commit performance.
Commits now store only what is changed, with the rest of content taken either from the base commit or from the current main commit.
Addresses issue #342
> Changed state representation to delta representation to improve commit performance

- piecrust/CHANGELOG.md
- piecrust/src/store.rs
- piecrust/src/store/session.rs
Write commit time improvements decrease the commit persistence time by more than 30%.
This is achieved by extra commit clone removal, extra commit retrieval removal, and index serialisation optimisation.
Implements issue #388
> Write commit time improvements

- piecrust/src/store.rs
- piecrust/src/store/session.rs
- piecrust/src/vm.rs
Remove `merkle.root()` calculation during bootstrap
Additionally:
- Add logs for new vm instantiation
- remove useless string clone
- move "calculating root" logs
> piecrust: improve bootstrap

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/store.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
- piecrust/src/vm.rs
- piecrust/tests/callcenter.rs
Speed up commit operations' handling of Merkle tree and contracts map storage
Implements issue #396
> Speed up commit operations' handling of Merkle tree and contracts map storage

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
- piecrust/src/store.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
To address page finding performance problem, separated base info file from the index file, thus speeding up access to base info and making it O(1) rather than dependent on the size of the index file
Implements issue #393
> separated base info from index

- piecrust/src/store.rs
- piecrust/src/store/commit.rs
- piecrust/src/store/session.rs
- piecrust/src/store/tree.rs
Optimises contract session to hold a base commit without a copy of contract index
Corresponds to a published release `0.26.1-rc.0`
Resolves issue #400
> Optimise contract session to hold a base commit without a copy of contract index

- contracts/crossover/src/lib.rs
- piecrust/tests/crossover.rs
Test for ICCs not rolled back when panic occurs at the bottom callee and it is not propagated up the chain
Implements issue #408
> piecrust: added test for ICCs not rolled back when panic

- contracts/Cargo.toml
- contracts/callcenter/src/lib.rs
- contracts/callstack/Cargo.toml
- contracts/callstack/src/lib.rs
- contracts/crossover/src/lib.rs
- piecrust-uplink/Cargo.toml
- piecrust-uplink/src/abi/state.rs
- piecrust/Cargo.toml
- piecrust/src/call_tree.rs
- piecrust/src/imports.rs
- piecrust/src/session.rs
- piecrust/src/store.rs
- piecrust/src/store/tree.rs
- piecrust/tests/callcenter.rs
- piecrust/tests/crossover.rs
Store merkle positions in binary rather than using rkyv.
This has the advantage of better and more stable performance, as well as
making the disk format explicit and not dependent on rkyv, hence easier
to maintain in the future.
Implements issue #410
> Store merkle positions in binary formant rather than using rkyv

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- piecrust-uplink/src/lib.rs
- piecrust-uplink/src/serde_support.rs
- piecrust-uplink/tests/serde.rs
For dusk-network/rusk/issues/2773 and #414
> Added serde feature

- piecrust-uplink/CHANGELOG.md
- piecrust-uplink/Cargo.toml
- Add serde `Serialize` and `Deserialize` implementations for `ContractId` and `Event` [#414]
- Add `serde`, `hex`, `base64` and `serde_json` optional dependencies [#414]
- Add `serde` feature [#414]
[0.17.2]: https://github.com/dusk-network/piecrust/compare/uplink-0.17.1...uplink-0.17.2
> uplink: bump version to `0.17.2`

- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/tests/callcenter.rs
Callstack returns callers id list without self id.
Implements issue #422
> callstack returns callers id list without self id

- contracts/callcenter/src/lib.rs
- piecrust/CHANGELOG.md
- piecrust/src/imports.rs
- piecrust/tests/initializer.rs
Functionality and test for blocking 'init' method to be called only during deployment.
Implements issue #433 
It will have a companion test in Rusk as well.
> blocking 'init' method to be called only during deployment

- piecrust/CHANGELOG.md
- piecrust/Cargo.toml
piecrust: version 0.28.0
contains:
performance improvements (including index file elimination)
init function fix
addresses: #396, #419, #433
> piecrust: version 0.28.0

- .github/workflows/ISSUE_TEMPLATE/bug_report.md
- README.md
- crumbles/README.md
- docs/on-disk-datastore.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "exhustive" to "exhaustive".
Corrected "fuctionality" to "functionality".
Corrected "When can" to "We can".
Corrected "ran" to "run". It should be "run" instead of "ran" as it refers to an action that can be performed in the future.
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- Makefile
- crumbles/src/lib.rs
- piecrust-uplink/src/abi/handlers.rs
- piecrust-uplink/src/lib.rs
- piecrust/src/instance.rs
- piecrust/src/session.rs
- rust-toolchain.toml
For https://github.com/dusk-network/rusk/issues/3470.
The rust version chosen is a 1.82.0 nightly (2024-07-30) because it uses LLVM 18. From LLVM 19, the reference-types feature is enabled by default, and I thought it would be a good idea to pick a toolchain that will require the least amount of changes.
> Upgrade toolchain
